feat: добавить хранилища, сервисы, API
Vahrimur/java-filmorate pull request #4
Opened 2022-06-19 21:56 UTC by Vahrimur

2022-06-20 07:51 UTC, kukolev requested changes

2022-06-20 07:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorResponse.java
> +    String error; // название ошибки
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-06-20 07:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmStorage getFilmStorage() {
По моему эти геттеры лишние. Если где-то потребуется сторедж, то его можно туда заинжектить, т.к. сторедж является бином.

2022-06-20 07:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Film addedFilm = filmService.getFilmStorage().addFilm(film);
Так делать не стоит, т.к. сервис теперь превращается в контейнер для класса FilmStorage и создается лишняя зависимость на класс FilmService. Тут возможны два альтернативных решения: 1) Сделать в FilmService метод addFilm и использовать его 2) Заинжектить в FilmController бин FilmStorage. Так проще будет тестировать код.

Также нужно поправить и в UserControl.

2022-06-21 10:51 UTC, Vahrimur commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorResponse.java
> +    String error; // название ошибки
Сделала оба поля приватными.

2022-06-21 10:51 UTC, Vahrimur commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmStorage getFilmStorage() {
Убрала геттеры хранилищ из сервисов.

2022-06-21 10:59 UTC, Vahrimur commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Film addedFilm = filmService.getFilmStorage().addFilm(film);
Заинджектила хранилища в контроллеры.

2022-06-22 07:37 UTC, kukolev approved these changes

2022-06-23 19:23 UTC, merged